language:  python

python:
  - "2.7"

before_script:
  - sudo apt-get install -qq poppler-utils

env:
    VERSION=plone-4.3

matrix:
  include:
     - python: "2.7"
       env: VERSION=plone-4.3
     - python: "2.7"
       env: VERSION=plone-5.0
     - python: "2.7"
       env: VERSION=plone-5.1
     - python: "2.7"

script: bash build_test.sh $VERSION 

